import React from "react";
import Footer from '../components/Footer';
import Header from '../components/Header';
import styles from '@/styles/Home.module.css'
import Head from 'next/head'
import { Inter } from 'next/font/google'
import { ConnectButton } from '@rainbow-me/rainbowkit';
import Image from 'next/image';
import FlipCard from "@/components/FlipCard";
import BackToTopButton from '@/components/BackToTop';

const inter = Inter({ subsets: ['latin'] })


export default function About() {
  return (
    <>
      <Head>
        <title>PIE-Techhhh</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={`${styles.main} ${inter.className}`}>
        <BackToTopButton />
        <div className={styles.description}>
          <Header />

        </div>


        <div className={styles.About}>
          <div className={styles.AboutText}>
          <h1>About PIE-Tech</h1> <br />
          <div className={styles.AboutTextDes}>
          
            <p>Welcome to PIE-Tech, your gateway to a revolutionary approach to digital identity. At PIE-Tech, we understand the significance of privacy, the power of interoperability, the efficiency of seamless processes, the trust that users place in our technology, 
            and the ever-evolving landscape of digital solutions.</p>
          <br/>
          <p>
          PIE-Tech envisions a world where individuals have absolute control over their digital identity, without compromising on privacy and security. We are committed to providing a cutting-edge platform that not only safeguards your personal information 
          but empowers you to harness the full potential of your digital presence.
          </p>
          </div>
          </div>
          <div className={styles.AboutImage}>
            <Image src="/images/logoeffect.gif" alt="Own Identity Inc Logo" width={300} height={300} />
          </div>
        </div>


        <div className={styles.About5Desc}>
          <div className={styles.About5DescBorder}>
            <div className={styles.AboutPrivacy}>
              <div className={styles.AboutPrivacyBox}>
                <div>
                  <p className={styles.AboutPrivacyTitle}>Privacy</p>
                </div>
                
            

                <div className={styles.AboutPrivacyDesc}>
                  <p>PIE-Tech safeguards your privacy with utmost diligence, ensuring that your personal data is treated with the highest level of confidentiality. We prioritize your security and empower you 
                      with control over your information, creating a trusted digital sanctuary.</p>
                </div>
              </div>

              <div className={styles.privacyspace}>
              </div>

              <div className={styles.AboutInter}>
                <div >
                  <p className={styles.AboutInteroperability}>Interoperability</p>
              
                  <div className={styles.AboutInteroperabilityDesc}>
                    <p>Experience unparalleled flexibility with PIE-Tech as it effortlessly integrates across various blockchains including Ethereum, Arbitrum, Optimism, Polygon and Sepolia. This unique interoperability empowers you to navigate the diverse 
                      blockchain landscape, maximizing the benefits of this cutting-edge technology.</p>

                  </div>
                </div>

              </div>

            </div>

            <div className={styles.AboutPrivacy}>
              <div className={styles.AboutEfficiency}>
                <div className={styles.AboutEfficiencyTitle}>
                  <p>Efficiency</p>
                </div>

                <div className={styles.AboutEfficiencyDesc}>
                  <p>Embrace seamless efficiency with PIE-Tech, available to you 24/7. Our platform is designed for constant accessibility, providing you with a responsive and dynamic digital experience whenever 
                    you need it. Your time is valuable, and we ensure it&apos;s never wasted.</p>
                </div>
              </div>

              <div className={styles.privacyspace}>
              </div>


              <div className={styles.AboutTrust}>
                <div className={styles.AboutTrustTitle}>
                  <p>Trust</p>
                </div>

                <div className={styles.AboutTrustDesc}>
                  <p>Your trust is our priority. PIE-Tech places control over your data firmly in your hands, building a relationship of confidence and reliability. Take charge of your digital identity and navigate 
                    the online world with the assurance that your trust is well-placed.</p>

                </div>
              </div>

            </div>

   
              <div className={styles.AboutTechnology}>
                <div className={styles.AboutTechnologyTitle}>
                <p>Technology</p>
                </div>

                <div className={styles.AboutTechnologyDesc}>
                  <p>PIE-Tech is at the forefront of innovation, combining advanced technologies like blockchain, smart contracts, hashing, and digital wallets (crypto wallets). This technological synergy guarantees a powerful and secure digital identity platform, giving you a competitive edge in 
                    the rapidly evolving digital landscape. Embrace the future with PIE-Tech.</p>
                </div>
              </div>
          </div>
        </div>




        <hr style={{
          background: 'white',
          color: 'white',
          borderColor: 'white',
          opacity:'30%',
          height: '2px',
          width:'70%',
          }}/>

        <div className={styles.About2}>
          <div className={styles.About2Text}>
          <div className={styles.About2TextQuotes1}>
            <p>&quot;</p>
            </div>
                <div className={styles.About2TextDesc}>
                  <p>Take back control of your own identity.</p>
                </div>
            <div className={styles.About2TextQuotes2}>
            <p>&rdquo;</p>
            </div>
            <p>Jean - Project Manager</p>
          </div>

          <div className={styles.About2Image}>
            <Image src="/images/aboutimage.png" alt="Own Identity Inc Logo" width={520} height={300} />
          </div>
        </div>


        


        <br /> <br /> <br /> <br /> <br /> <br /><br /><br />

        <div className={styles.Footer}>
          <div>
            <Footer />
          </div>
        </div>
      </main>
    </>
  );
}
